// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package locales

import (
	"golang.org/x/text/language"

	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

var Catalog catalog.Catalog

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}

	Catalog = cat

}

var messageKeyToIndex = map[string]int{
	"Cannot find JSONDict key": 2,
	"Illformat":                12,
	"do not known how to deserialize json into this interface type": 14,
	"fail to insert object":           5,
	"invalid 4 byte rune":             20,
	"invalid char":                    16,
	"invalid hex":                     7,
	"key not found":                   13,
	"map key must be string":          11,
	"missing input field":             3,
	"nil input field":                 6,
	"not a valid JSONArray":           0,
	"not a valid JSONDict":            9,
	"not a valid boolean":             4,
	"not a valid float":               17,
	"not a valid number":              15,
	"not a valid string":              19,
	"out of index range":              21,
	"out of key range":                8,
	"unmarshal array length mismatch": 10,
	"unmarshal type mismatch":         18,
	"unsupported operation":           1,
}

var en_USIndex = []uint32{ // 23 elements
	0x00000000, 0x00000016, 0x0000002c, 0x00000045,
	0x00000059, 0x0000006d, 0x00000083, 0x00000093,
	0x0000009f, 0x000000b0, 0x000000c5, 0x000000e5,
	0x000000fc, 0x00000106, 0x00000114, 0x00000152,
	0x00000165, 0x00000172, 0x00000184, 0x0000019c,
	0x000001af, 0x000001c3, 0x000001d6,
} // Size: 116 bytes

const en_USData string = "" + // Size: 470 bytes
	"\x02not a valid JSONArray\x02unsupported operation\x02Cannot find JSONDi" +
	"ct key\x02missing input field\x02not a valid boolean\x02fail to insert o" +
	"bject\x02nil input field\x02invalid hex\x02out of key range\x02not a val" +
	"id JSONDict\x02unmarshal array length mismatch\x02map key must be string" +
	"\x02Illformat\x02key not found\x02do not known how to deserialize json i" +
	"nto this interface type\x02not a valid number\x02invalid char\x02not a v" +
	"alid float\x02unmarshal type mismatch\x02not a valid string\x02invalid 4" +
	" byte rune\x02out of index range"

var zh_CNIndex = []uint32{ // 23 elements
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000,
} // Size: 116 bytes

const zh_CNData string = ""

// Total table size 702 bytes (0KiB); checksum: 7CB08ED6
